plugins:
  hot_topics_enabled:
    default: true
    client: true
  hot_topics_gravity_rate:
    default: 1.5
    client: true
  hot_topics_boost_value:
    default: 0.1
    client: true
  hot_topics_calc_period:
    default: 30
    client: true
  hot_topics_only_op_likes:
    default: false
    client: true